export * from './activity.model';
export * from './course.model';
export * from './department.model';
export * from './module.model';
export * from './offering.model';
export * from './prefix.model';
export * from './resource.model';
export * from './term.model';
export * from './topic.model';
